(define nil '())
(define (same-parity . l)
  (if (= 0 (remainder (car l) 2))
    (pre-map l (lambda (x) (= 0 (remainder x 2))))
    (pre-map l (lambda (x) (not (= 0 (remainder x 2)))))))
(define (pre-map x predict)
  (cond ((null? x) nil)
        ((predict (car x)) (cons (car x) (pre-map (cdr x) predict)))
        (else (pre-map (cdr x) predict))))
